# Use the official PostgreSQL 15 image
FROM postgres:15

# Add the SQL script to the container
COPY InsertExtendedUsers.sql /docker-entrypoint-initdb.d/

# By default, the SQL files in /docker-entrypoint-initdb.d/ will be executed on container startup
